version = 0.1

[default.deploy.parameters]
stack_name = "membership-service-mena"
resolve_s3 = true
s3_prefix = "membership-service-mena"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
