version = 0.1

[default.deploy.parameters]
stack_name = "membership-service"
resolve_s3 = true
s3_prefix = "membership-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
